title: Tkinter Python
description: 'In this course, i have developed various software GUI using Python , tkinter.'
template:
  repo: tkinter-python-template
  name: tkinter-python
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
